version: "3.6"

services:

  database:
    image: mysql:5.7
    env_file: MYSQL.env

  db_init:
    build: .
    env_file: MYSQL.env
    entrypoint:
      - /app/database_waiting.sh
      - python
      - /app/db_init.py
    volumes:
      - .:/app:ro

  api_point:
    build: .
    env_file: MYSQL.env
    ports:
      - 8080:8080
    entrypoint:
      - /app/database_waiting.sh
      - gunicorn
      - -b
      - 0.0.0.0:8080
      - /app/api:api
    volumes:
      - .:/app:ro
