version: "3.6"

services:

  database:
    image: mysql:5.7
    env_file: MYSQL.env

  db_init:
    build: .
    env_file: MYSQL.env
    entrypoint:
      - "python"
      - "/app/db_init.py"
    volumes:
      - .:/app:ro






